
name: github -- Gitee
on:

  push:
    branches: ["master"]
      # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # 同步代码 gitee
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:bealei/zl.git
          # 注意替换为你的 Gitee 目标仓库地址.
          destination-repo: git@gitee.com:bealei/zl.git